name: pinquest
description: A comprehensive location-based discovery app with gamification features
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Material Design
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.1.1
  
  # Maps & Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  geolocator: ^10.1.0
  maps_launcher: ^2.2.1
  
  # Firebase & Authentication
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  
  # Image & Media
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # Local Storage & Offline
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/mock_data/
